### PR TITLE
Week 2: _Lesson 3_

### PR DESCRIPTION
**Pull request by joseandresgavilanes**
### Week 2: _Lesson 3_
- Semantic HTML
1. Change the tags in your CV, in order to use Semantic HTML.
2. Make a fork of Week's 2 repository.
3. Make a Pull Request.
image

### CODE REVIEW

**Comment by joseandresgavilanes** [comment]
### Week 2: _Lesson 4_
- Forms

1. Add to your CV a new contact page where you use forms.
2. Prevent the default behavior when sending information to the server.

image

**Comment by santiago01est** [comment]
Hola joseandresgavilanes, excelente trabajo, Semantic HTML 👍 , formulario 💯

**Review by facu1391 — APPROVED** [review]
Todo se puede ver perfecto! tienes mi Approve, podrías revisar mi PR?  #88

**Review by santiago01est — COMMENTED** [review]
excelente trabajo

**Pull request closed without merging**
