### PR TITLE
Pull request gustavo.arana6562

### PR DESCRIPTION
**Pull request by gustavo-arana**
# Steps to resolve exercise

1. Prepare your GitHub account:
    * Create or sign up for an account on [GitHub](https://github.com/)
    > If this link doesn´t work, copy and paste this URL into your browser ****https://github.com/****

    * Open this [link](https://gitgub.com/undefined-academy/semana-2) containing the repository to fork: Repository **semana-2**
    > If this link doesn´t work, copy and paste this URL into your browser ****https://gitgub.com/undefined-academy/semana-2****
    
2. On the **semana-2** repository, click on the **Fork** button and select **Create a new fork**
    > This action creates a copy of the **semana-2** repository in your GitHub account.

3. Open your terminal and execute the command `git clone [URL_OF_YOUR_FORKED_REPOSITORY]`
    * Open your forked repository on a browser
    * Click the **Code** button
    * Click the **SSH** tab
    * Copy the URL of your repository
    * Execute the command `git clone [URL_OF_YOUR_FORKED_REPOSITORY]` in your console
    > For example, `git clone git@github.com:gustavo-arana/semana-2.git`

4. Change to the folder of the repository with the command `cd semana-2`

5. Create a directory in the **github-profiles** a folder with the command `mkdir NAME_DIRECTORY`
    > The **NAME_DIRECTORY** will be your nickname on Discord and your account number: **gustavo.arana-6562**

6. Create a file named **index.html** with the command `touch index.html` and complete your profile with structure about html semantic

7. Commit the changes:
    * `git pull origin main` -> Check the changes on the remote repository
    * `git add .` -> Add new files
    * `git commit -m "CV Html Semantic"` -> Commit changes
    * `git push origin main` -> Send changes to the remote repository

8. On your remote repository on the browser, click on the **Pull request** tab
    > You will see a **Comparing changes** section and the option to **Create pull request** to the base repository: undefined-academy/semana-2.

### CODE REVIEW

**Review by DevOld112 — APPROVED** [review]
Hola Gustavo, cómo te va?

Tienes todo lo requerido para los ejercicios, un código fácil de leer y entendible, sigue así.

**Comment by gustavo-arana** [comment]
Gracias, DevOld

**Comment by joseandresgavilanes** [comment]
### Hello Gustavo! 
Great job, **I really liked** the way you explained the process in the PR. **_Nothing to complain about, good job and keep going!_**

**Review by joseandresgavilanes — APPROVED** [review]
### **Hello Gustavo!**
Great job, I really liked the way you explained the process in the PR. _**Nothing to complain about, good job and keep going!**_

**Pull request merged**
